version: '3.5'
services:
  api-test:
    build:
      context: ..
      target: build
    working_dir: /src
    command:
      - dotnet
      - test
    environment:
      - COUCHBASE_CONNECTION_STRING=couchbase://couchbase-server
      - COUCHBASE_USERNAME=Administrator
      - COUCHBASE_PASSWORD=password
      - COUCHBASE_BUCKET_NAME=testbucket
    depends_on:
      - couchbase-server
    volumes:
      - ./nodestatus:/nodestatus
  couchbase-server:
    image: btburnett3/couchbasefakeit:enterprise-6.5.0 #couchbase:community-6.5.1
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    environment:
      - CB_USERNAME=Administrator
      - CB_PASSWORD=password
    volumes:
      - ./nodestatus:/nodestatus