name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Run CouchbaseFakeIt
      uses: brantburnett/run-couchbasefakeit@v0.1
      with:
        couchbase-version: enterprise-6.5.0
        couchbase-configuration: couchbase # Refers to the couchbase folder
    - name: Install dependencies
      run: dotnet restore IntegrationTestPractice
    - name: Test
      run: dotnet test IntegrationTestPractice.Tests --verbosity normal
      env:
        COUCHBASE_CONNECTION_STRING: couchbase://localhost
        COUCHBASE_USERNAME: Administrator
        COUCHBASE_PASSWORD: password
        COUCHBASE_BUCKET_NAME: testbucket
