name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        working-directory: src
        run: docker-compose --file ci/docker-compose.test.yml build

      - name: Run api tests
        working-directory: src
        run: docker-compose --file ci/docker-compose.test.yml run api-test
